package br.com.bradescoseguros.opin.common;

import br.com.bradescoseguros.opin.domain.residential.*;
import br.com.bradescoseguros.opin.dummy.DummyObjectsUtil;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;

import java.math.BigDecimal;
import java.util.List;

public class HomeInsuranceTestUtil {

	public static final String REAL = "REAL";
	public static final String CODE_REAL = "R$";
	public static final String COVERAGE_DETAIL = "coverageDetail";

	public static ResidentialDomain getResidentialDomain() {
		final ResidentialDomain residentialDomain = DummyObjectsUtil.newInstance(ResidentialDomain.class);
		final ProductDomain product = getProductDomain();
		residentialDomain.setProduct(product);

		return residentialDomain;
	}

	public static ProductDomain getProductDomain() {
		var product = DummyObjectsUtil.newInstance(ProductDomain.class);
		product.setPropertyCharacteristics(List.of(PropertyCharacteristics.builder()
						.destinationInsuredImportance(HomeInsurancePropertyCharacteristics.DestinationInsuredImportanceEnum.PREDIO.getValue())
						.propertyBuildType(HomeInsurancePropertyCharacteristics.PropertyBuildTypeEnum.ALVENARIA.getValue())
						.propertyType(HomeInsurancePropertyCharacteristics.PropertyTypeEnum.APARTAMENTO.getValue())
						.propertyUsageType(HomeInsurancePropertyCharacteristics.PropertyUsageTypeEnum.ALUGUEL_TEMPORADA.getValue())
						.build()));
		product.setValidity(List.of(Validity.builder()
						.term(HomeInsuranceValidity.TermEnum.PLURIANUAL.getValue())
						.termOthers("termOthers")
						.build()));
		product.setTargetAudiences(List.of(HomeInsuranceProduct.TargetAudiencesEnum.PESSOA_NATURAL.getValue()));
		product.setTermsAndConditions(List.of(TermsAndConditions.builder()
						.susepProcessNumber("123456789")
						.definition("definition")
						.build()));
		product.setAdditional(List.of(HomeInsuranceProduct.AdditionalEnum.CASHBACK.getValue()));
		product.setCustomerServices(List.of(HomeInsuranceProduct.CustomerServicesEnum.LIVRE_ESCOLHA.getValue()));
		product.setPremiumPayments(List.of(PremiumPayment.builder()
						.paymentMethod(HomeInsurancePremiumPayment.PaymentMethodEnum.CARTAO_CREDITO.getValue())
						.paymentMethodDetail("paymentMethodDetail")
						.paymentType(HomeInsurancePremiumPayment.PaymentTypeEnum.PAGAMENTO_UNICO.getValue())
						.build()));
		product.setAssistanceServices(List.of(ComplementaryAssistanceService.builder()
						.assistanceServicesPackage(HomeInsuranceAssistanceServices.AssistanceServicesPackageEnum.ATE_10_SERVICOS.getValue())
						.assistanceServicesDetail("complementaryAssistanceServicesDetail")
						.chargeTypeSignaling("GRATUITA")
						.build()));
		product.setCoverages(List.of(Coverages.builder()
										.coverageType(HomeInsuranceCoverages.CoverageTypeEnum.ALAGAMENTO.getValue())
										.coverageDetail(COVERAGE_DETAIL)
										.coveragePermissionSeparateAcquisition(true)
										.coverageAttributes(CoverageAttributes.builder()
														.maxLMI(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("1000.5"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.minLMI(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("900.50"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.minDeductibleAmount(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("10.00"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.insuredMandatoryParticipationPercentage(10)
														.build())
										.build(),
						Coverages.builder()
										.coverageType(HomeInsuranceCoverages.CoverageTypeEnum.PAISAGISMO.getValue())
										.coverageDetail(COVERAGE_DETAIL)
										.coveragePermissionSeparateAcquisition(true)
										.coverageAttributes(CoverageAttributes.builder()
														.maxLMI(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("3500.5"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.minLMI(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("800.50"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.minDeductibleAmount(CoverageAttributesDetails.builder()
																		.amount(new BigDecimal("20.00"))
																		.unit(CoverageAttributesDetailsUnit.builder()
																						.code(CODE_REAL)
																						.description(REAL)
																						.build())
																		.build())
														.insuredMandatoryParticipationPercentage(10)
														.build())
										.build()));
		product.setMinimumRequirements(List.of(MinimumRequirement.builder()
						.contractingType(HomeInsuranceMinimumRequirements.ContractingTypeEnum.INDIVIDUAL.getValue())
						.contractingMinRequirement("contractingMinRequirement")
						.build()));
		product.setPremiumRates(List.of("premiumRate"));
		return product;
	}
}