package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static com.mongodb.assertions.Assertions.assertNotNull;
import static com.mongodb.assertions.Assertions.assertNull;
import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
class CommonMappingsTest {

	private static final String INVALID_TYPE = "invalidType";

	@Test
	@Tag("unit")
	void mapAttributesDetailsAmountFrom_withValidScale_shouldReturnAmount() {

		//Arrange
		final BigDecimal amount = new BigDecimal("120.00");

		//Act
		final BigDecimal response = CommonMappings.INSTANCE.mapAttributesDetailsAmountFrom(amount);

		//Asserts
		assertThat(response).isEqualTo(amount);
	}

	@Test
	@Tag("unit")
	void mapAttributesDetailsAmountFrom_withInvalidScale_shouldReturnAmountWithCorrectScale() {

		//Arrange
		final BigDecimal amount = new BigDecimal("120.0");

		//Act
		final BigDecimal response = CommonMappings.INSTANCE.mapAttributesDetailsAmountFrom(amount);

		//Asserts
		assertThat(response).isEqualTo("120.00");
	}

	@Test
	@Tag("unit")
	void mapAttributesDetailsAmountFrom_withNullValue_shouldReturnNull() {
		//Act
		assertThat(CommonMappings.INSTANCE.mapAttributesDetailsAmountFrom(null)).isNull();
	}

	@Test
	@Tag("unit")
	void mapCoverageTypeFrom_withCoverageType_shouldReturnCoverageTypeEnum() {

		//Act
		final HomeInsuranceCoverages.CoverageTypeEnum alagamento = CommonMappings.INSTANCE.mapCoverageTypeFrom("ALAGAMENTO");

		//Asserts
		assertThat(alagamento).isEqualTo(HomeInsuranceCoverages.CoverageTypeEnum.ALAGAMENTO);

	}

	@Test
	@Tag("unit")
	void mapCoverageTypeFrom_withInvalidCoverageType_shouldReturnNull() {

		//Act
		final HomeInsuranceCoverages.CoverageTypeEnum coverageType = CommonMappings.INSTANCE.mapCoverageTypeFrom("invalid");

		//Asserts
		assertThat(coverageType).isNull();
	}

	@Test
	@Tag("unit")
	void mapCoverageTypeFrom_withEmptyValue_shouldReturnNull() {

		//Act
		final HomeInsuranceCoverages.CoverageTypeEnum coverageType = CommonMappings.INSTANCE.mapCoverageTypeFrom("");

		//Asserts
		assertThat(coverageType).isNull();
	}

	@Test
	@Tag("unit")
	void mapAdditionalEnumFrom_withValidValue_shouldReturnAdditionalEnum() {

		//Arrange
		final String additionalType = "SORTEIO_GRATUITO";

		//Act
		final HomeInsuranceProduct.AdditionalEnum additional = CommonMappings.INSTANCE.mapAdditionalEnumFrom(additionalType);

		//Asserts
		assertThat(additional.getValue())
						.isNotEmpty()
						.isEqualTo(additionalType);
	}

	@Test
	@Tag("unit")
	void mapAdditionalEnumFrom_withInvalidValue_shouldReturnNull() {
		//Act
		assertThat(CommonMappings.INSTANCE.mapAdditionalEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapCustomerServicesEnumFrom_withAListOfValues_shouldReturnListOfCustomerServices() {

		//Arrange
		final List<String> services = Arrays.asList("REDE_REFERENCIADA", "LIVRE_ESCOLHA", "REDE_REFERENCIADA_LIVRE_ESCOLHA");

		//Act
		final List<HomeInsuranceProduct.CustomerServicesEnum> customerServiceEnums = CommonMappings.INSTANCE.mapCustomerServicesEnumFrom(services);

		//Asserts
		assertThat(customerServiceEnums.size()).isEqualTo(services.size());

		final List<String> customerServices = customerServiceEnums.stream().map(HomeInsuranceProduct.CustomerServicesEnum::getValue).collect(Collectors.toList());
		assertThat(customerServices).containsExactlyInAnyOrderElementsOf(services);
	}

	@Test
	@Tag("unit")
	void mapCustomerServicesEnumFrom_withOneInvalidValue_shouldReturnAnIncompleteListOfCustomerServices() {

		//Arrange
		final List<String> services = Arrays.asList("REDE_REFERENCIADA", INVALID_TYPE, "REDE_REFERENCIADA_LIVRE_ESCOLHA");

		//Act
		final List<HomeInsuranceProduct.CustomerServicesEnum> customerServiceEnums = CommonMappings.INSTANCE.mapCustomerServicesEnumFrom(services);

		//Asserts
		assertThat(customerServiceEnums.size()).isEqualTo(services.size());
		assertThat(customerServiceEnums).containsNull();
	}

	@Test
	@Tag("unit")
	void mapTargetAudienceFrom_withValidValue_shouldReturnHomeInsuranceTargetAudience() {

		//Arrange
		final String targetAudience = "PESSOA_NATURAL";

		//Act
		final List<HomeInsuranceProduct.TargetAudiencesEnum> homeInsuranceTargetAudience = CommonMappings.INSTANCE.mapTargetAudienceFrom(List.of(targetAudience));

		//Asserts
		assertThat(homeInsuranceTargetAudience.get(0).getValue())
						.isNotEmpty()
						.isEqualTo(targetAudience);
	}

	@Test
	@Tag("unit")
	void mapTargetAudienceFrom_withInvalidValue_shouldReturnNull() {

		// Act
		List<HomeInsuranceProduct.TargetAudiencesEnum> result = CommonMappings.INSTANCE.mapTargetAudienceFrom(List.of(INVALID_TYPE));

		// Assert
		assertNotNull(result);
		assertNull(result.get(0));
	}

	@Test
	@Tag("unit")
	void mapAssistanceServicesPackageEnumFrom_withValidValue_shouldReturnAssistanceServicesPackageEnum() {

		//Arrange
    	final String assistanceService = "ATE_10_SERVICOS";

		//Act
		final HomeInsuranceAssistanceServices.AssistanceServicesPackageEnum assistanceServicesPackageEnum = CommonMappings.INSTANCE.mapAssistanceServicesPackageEnumFrom(assistanceService);

		//Asserts
		assertThat(assistanceServicesPackageEnum.getValue())
						.isNotEmpty()
						.isEqualTo(assistanceService);
	}

	@Test
	@Tag("unit")
	void mapAssistanceServicesPackageEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapAssistanceServicesPackageEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapChargeTypeSignalingEnumFrom_withValidValue_shouldReturnChargeTypeSignalingEnum() {
		//Arrange
		final String chargeType = "GRATUITA";

		//Act
		final HomeInsuranceAssistanceServices.ChargeTypeSignalingEnum chargeTypeSignalingEnum = CommonMappings.INSTANCE.mapChargeTypeSignalingEnumFrom(chargeType);

		//Asserts
		assertThat(chargeTypeSignalingEnum.getValue())
						.isNotEmpty()
						.isEqualTo(chargeType);
	}

	@Test
	@Tag("unit")
	void mapChargeTypeSignalingEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapChargeTypeSignalingEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapPropertyUsageTypeEnumFrom_withValidValue_shouldReturnPropertyUsageTypeEnum() {

		//Arrange
		final String propertyUsageType = "HABITUAL";

		//Act
		final HomeInsurancePropertyCharacteristics.PropertyUsageTypeEnum propertyUsageTypeEnum = CommonMappings.INSTANCE.mapPropertyUsageTypeEnumFrom(propertyUsageType);

		//Asserts
		assertThat(propertyUsageTypeEnum.getValue())
						.isNotEmpty()
						.isEqualTo(propertyUsageType);
	}

	@Test
	@Tag("unit")
	void mapPropertyUsageTypeEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapPropertyUsageTypeEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapPropertyBuildTypeEnumFrom_withValidValue_shouldReturnPropertyBuildTypeEnum() {

		//Arrange
		final String propertyBuildType = "ALVENARIA";

		//Act
		final HomeInsurancePropertyCharacteristics.PropertyBuildTypeEnum propertyBuildTypeEnum = CommonMappings.INSTANCE.mapPropertyBuildTypeEnumFrom(propertyBuildType);

		//Asserts
		assertThat(propertyBuildTypeEnum.getValue())
						.isNotEmpty()
						.isEqualTo(propertyBuildType);
	}

	@Test
	@Tag("unit")
	void mapPropertyBuildTypeEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapPropertyBuildTypeEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapPropertyTypeEnumFrom_withValidValue_shouldReturnPropertyTypeEnum() {

		//Arrange
		final String propertyType = "CASA";

		//Act
		final HomeInsurancePropertyCharacteristics.PropertyTypeEnum propertyTypeEnum = CommonMappings.INSTANCE.mapPropertyTypeEnumFrom(propertyType);

		//Asserts
		assertThat(propertyTypeEnum.getValue())
						.isNotEmpty()
						.isEqualTo(propertyType);
	}

	@Test
	@Tag("unit")
	void mapPropertyTypeEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapPropertyTypeEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapDestinationInsuredImportanceEnum_withValidValue_shouldReturnDestinationInsuredImportanceEnum() {

		//Arrange
		final String importanceInsuredType = "PREDIO";

		//Act
		final HomeInsurancePropertyCharacteristics.DestinationInsuredImportanceEnum importanceInsuredEnum = CommonMappings.INSTANCE.mapDestinationInsuredImportanceEnum(importanceInsuredType);

		//Asserts
		assertThat(importanceInsuredEnum.getValue())
						.isNotEmpty()
						.isEqualTo(importanceInsuredType);
	}

	@Test
	@Tag("unit")
	void mapDestinationInsuredImportanceEnum_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapDestinationInsuredImportanceEnum(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapPaymentMethodEnumFrom_withValidValue_shouldReturnPaymentMethodEnum() {

		//Arrange
		final String paymentMethodType = "CARTAO_CREDITO";

		//Act
		final HomeInsurancePremiumPayment.PaymentMethodEnum paymentMethodEnum = CommonMappings.INSTANCE.mapPaymentMethodEnumFrom(paymentMethodType);

		//Asserts
		assertThat(paymentMethodEnum.getValue())
						.isNotEmpty()
						.isEqualTo(paymentMethodType);
	}

	@Test
	@Tag("unit")
	void mapPaymentMethodEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapPaymentMethodEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapPaymentTypeEnumFrom_withValidValue_shouldReturnPaymentTypeEnum() {

		//Arrange
		final String paymentType = "PAGAMENTO_UNICO";

		//Act
		final HomeInsurancePremiumPayment.PaymentTypeEnum paymentTypeEnum = CommonMappings.INSTANCE.mapPaymentTypeEnumFrom(paymentType);

		//Asserts
		assertThat(paymentTypeEnum.getValue())
						.isNotEmpty()
						.isEqualTo(paymentType);
	}

	@Test
	@Tag("unit")
	void mapPaymentTypeEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		assertThat(CommonMappings.INSTANCE.mapPaymentTypeEnumFrom(INVALID_TYPE)).isNull();
	}

	@Test
	@Tag("unit")
	void mapTermEnumFrom_withValidValue_shouldReturnTermEnum() {

		//Arrange
		final String term = "ANUAL";

		//Act
		final HomeInsuranceValidity.TermEnum termEnum = CommonMappings.INSTANCE.mapTermEnumFrom(term);

		//Asserts
		assertThat(termEnum.getValue()).isEqualTo(term);
	}

	@Test
	@Tag("unit")
	void mapTermEnumFrom_withInvalidValue_shouldReturnNull() {

		//Act
		final HomeInsuranceValidity.TermEnum termEnum = CommonMappings.INSTANCE.mapTermEnumFrom(INVALID_TYPE);

		//Asserts
		assertThat(termEnum).isNull();
	}

	@Test
	@Tag("unit")
	void mapContractingTypeFrom_withValidValue_shouldReturnContractingType() {

		//Arrange
		final String contracting = "COLETIVO";

		//Act
		final HomeInsuranceMinimumRequirements.ContractingTypeEnum contractingTypeEnum = CommonMappings.INSTANCE.mapContractingTypeFrom(contracting);

		//Asserts
		assertThat(contractingTypeEnum.getValue())
						.isNotEmpty()
						.isEqualTo(contracting);

	}

	@Test
	@Tag("unit")
	void mapContractingTypeFrom_withInvalidValue_shouldReturnNull() {

		//Act
		final HomeInsuranceMinimumRequirements.ContractingTypeEnum contractingTypeEnum = CommonMappings.INSTANCE.mapContractingTypeFrom(INVALID_TYPE);

		//Asserts
		assertThat(contractingTypeEnum).isNull();
	}
}