package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.common.HomeInsuranceTestUtil;
import br.com.bradescoseguros.opin.domain.residential.*;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;
import br.com.bradescoseguros.opin.interfaceadapter.util.NumberUtil;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
class ProductMapperTest {

	@Test
	@Tag("unit")
	void mapHomeInsuranceProductFrom_withProductDomain_shouldReturnHomeInsuranceProduct() {

		//Arrange
		final ProductDomain productDomain = HomeInsuranceTestUtil.getProductDomain();

		//Act
		final HomeInsuranceProduct homeInsuranceProduct = ProductMapper.INSTANCE.mapHomeInsuranceProductFrom(productDomain);

		//Asserts
		assertHomeInsuranceProduct(productDomain, homeInsuranceProduct);
	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceProductFrom_withNullProductDomain_shouldReturnNull() {

		//Act
		final HomeInsuranceProduct homeInsuranceProduct = ProductMapper.INSTANCE.mapHomeInsuranceProductFrom(null);

		//Asserts
		assertThat(homeInsuranceProduct).isNull();
	}

	@Test
	@Tag("unit")
	void mapHomeInsuranceAssistanceServicesFrom_withListOfComplementaryAssistance_shouldReturnHomeInsuranceAssistanceServices() {

		//Arrange
		final List<ComplementaryAssistanceService> assistanceServices = HomeInsuranceTestUtil.getProductDomain().getAssistanceServices();

		//Act
		final List<HomeInsuranceAssistanceServices> homeInsuranceAssistanceServices = ProductMapper.INSTANCE.mapHomeInsuranceAssistanceServicesFrom(assistanceServices);

		//Asserts
		assertHomeInsuranceAssistanceServices(assistanceServices, homeInsuranceAssistanceServices);
	}

	@Test
	@Tag("unit")
	void mapHomeInsuranceAssistanceServicesFrom_withEmptyList_shouldReturnHomeInsuranceAssistanceServicesEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapHomeInsuranceAssistanceServicesFrom(Collections.emptyList())).isEmpty();
	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceAssistanceServicesFrom_withNullEmpty_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapHomeInsuranceAssistanceServicesFrom(null)).isEmpty();
	}

	@Test
	@Tag("unit")
	void mapPropertyCharacteristicsFrom_withListOfPropertyCharacteristics_shouldReturnHomeInsurancePropertyCharacteristics() {

		//Arrange
		final List<PropertyCharacteristics> propertyCharacteristics = HomeInsuranceTestUtil.getProductDomain().getPropertyCharacteristics();

		//Act
		final List<HomeInsurancePropertyCharacteristics> homeInsuranceAssistanceServices = ProductMapper.INSTANCE.mapPropertyCharacteristicsFrom(propertyCharacteristics);

		//Asserts
		assertHomeInsurancePropertyCharacteristics(propertyCharacteristics, homeInsuranceAssistanceServices);
	}

	@Test
	@Tag("mutation")
	void mapPropertyCharacteristicsFrom_withNullList_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapPropertyCharacteristicsFrom(null)).isEmpty();
	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceCoveragesFrom_withNullCoverages_shouldReturnNull() {

		//Act
		final HomeInsuranceCoverages homeInsuranceCoverages = ProductMapper.INSTANCE.mapHomeInsuranceCoveragesFrom(null);

		//Asserts
		assertThat(homeInsuranceCoverages).isNull();
	}

	@Test
	@Tag("mutation")
	void mapCoverageAttributes_withCoverageAttributes_shouldReturnCoverageAttributes() {

		//Arrange
		final CoverageAttributes coverageAttributes = HomeInsuranceTestUtil.getProductDomain().getCoverages().get(0).getCoverageAttributes();

		//Act
		final HomeInsuranceCoverageAttributes homeInsuranceCoverageAttributes = ProductMapper.INSTANCE.mapCoverageAttributes(coverageAttributes);

		//Assertions
		assertCoverageAttributes(coverageAttributes, homeInsuranceCoverageAttributes);
	}

	@Test
	@Tag("mutation")
	void mapCoverageAttributes_withNullCoverageAttributes_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapCoverageAttributes(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapCoverageAttributesDetails_withNullCoverageAttributesDetails_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapCoverageAttributesDetails(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceCoverageAttributesDetailsUnit_withNullCoverageAttributesDetailsUnit_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapHomeInsuranceCoverageAttributesDetailsUnit(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapAssistanceServiceFrom_withNullComplementaryAssistanceService_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapAssistanceServiceFrom(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapPropertyCharacteristic_withNullPropertyCharacteristics_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapPropertyCharacteristic(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapPremiumPayment_withNullPremiumPayment_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapPremiumPayment(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapValidityFrom_withNullListOfValidity_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapValidityFrom(null)).isEmpty();
	}

	@Test
	@Tag("mutation")
	void mapValidityItemFrom_withNullValidity_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapValidityItemFrom(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapMinimumRequirements_withNullMinimumRequirement_shouldReturnNull() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapMinimumRequirements(null)).isNull();
	}

	@Test
	@Tag("mutation")
	void mapPremiumPaymentsFrom_withNullListOfPremiumPayment_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapPremiumPaymentsFrom(null)).isEmpty();
	}

	@Test
	@Tag("unit")
	void mapMinimumRequirementsItemsFrom_withMinimumRequirementsList_shouldMapMinimumRequirementsList() {

		//Arrange
		final MinimumRequirement minimumRequirement = MinimumRequirement
						.builder()
							.contractingType("INDIVIDUAL")
						.contractingMinRequirement("contractingMinRequirement")
						.build();

		//Act
		final List<HomeInsuranceMinimumRequirements> homeInsuranceMinimumRequirements = ProductMapper.INSTANCE.mapMinimumRequirementsItemsFrom(List.of(minimumRequirement));

		assertThat(homeInsuranceMinimumRequirements).isNotEmpty();
		final HomeInsuranceMinimumRequirements homeInsuranceRequirements = homeInsuranceMinimumRequirements.get(0);

		assertThat(homeInsuranceRequirements.getContractingMinRequirement()).isEqualTo(minimumRequirement.getContractingMinRequirement());
		assertThat(homeInsuranceRequirements.getContractingType().getValue()).isEqualTo(minimumRequirement.getContractingType());
	}

	@Test
	@Tag("unit")
	void mapMinimumRequirementsItemsFrom_withEmptyListOfMinimumRequirements_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapMinimumRequirementsItemsFrom(Collections.emptyList())).isEmpty();

	}

	@Test
	@Tag("unit")
	void mapMinimumRequirementsItemsFrom_whenMinimumRequirementsListIsNull_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapMinimumRequirementsItemsFrom(null)).isEmpty();

	}

	@Test
	@Tag("unit")
	void mapAdditionalEnumItemsFrom_withAdditionalList_shouldMapAdditionalList() {

		final String additional = "SORTEIO_GRATUITO";

		//Act
		final List<HomeInsuranceProduct.AdditionalEnum> additionalEnums = ProductMapper.INSTANCE.mapAdditionalEnumItemsFrom(List.of(additional));

		//Assert
		assertThat(additionalEnums).isNotEmpty();
		assertThat(additionalEnums.get(0).getValue()).isEqualTo(additional);
	}

	@Test
	@Tag("unit")
	void mapAdditionalEnumItemsFrom_withAdditionalListIsNull_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapAdditionalEnumItemsFrom(null)).isEmpty();

	}

	@Test
	@Tag("unit")
	void mapAdditionalEnumItemsFrom_withEmptyListOfAdditional_shouldReturnAnEmptyList() {

		//Act
		assertThat(ProductMapper.INSTANCE.mapAdditionalEnumItemsFrom(Collections.emptyList())).isEmpty();

	}


	private void assertCoverageAttributes(final CoverageAttributes coverageAttributes, final HomeInsuranceCoverageAttributes homeInsuranceCoverageAttributes) {
		assertThat(homeInsuranceCoverageAttributes).isNotNull();
		assertThat(homeInsuranceCoverageAttributes.getInsuredMandatoryParticipationPercentage()).isEqualTo(BigDecimal.valueOf(coverageAttributes.getInsuredMandatoryParticipationPercentage()));

		assertCoverageDetails(coverageAttributes.getMaxLMI(), homeInsuranceCoverageAttributes.getMaxLMI());
		assertCoverageDetails(coverageAttributes.getMinLMI(), homeInsuranceCoverageAttributes.getMinLMI());
		assertCoverageDetails(coverageAttributes.getMinDeductibleAmount(), homeInsuranceCoverageAttributes.getMinDeductibleAmount());
	}

	private void assertCoverageDetails(final CoverageAttributesDetails coverageAttributesDetails, final HomeInsuranceCovaregeAttibutesDetails homeInsuranceCovaregeAttibutesDetails) {
		assertThat(homeInsuranceCovaregeAttibutesDetails).isNotNull();
		assertThat(homeInsuranceCovaregeAttibutesDetails.getAmount()).isEqualTo(NumberUtil.formatBigDecimalNumber(coverageAttributesDetails.getAmount()));

		assertCoverageAttributesDetailsUnit(coverageAttributesDetails.getUnit(), homeInsuranceCovaregeAttibutesDetails.getUnit());
	}

	private void assertCoverageAttributesDetailsUnit(final CoverageAttributesDetailsUnit coverageAttributesDetailsUnit, final HomeInsuranceCovaregeAttibutesDetailsUnit homeInsuranceCovaregeAttibutesDetailsUnit) {
		assertThat(homeInsuranceCovaregeAttibutesDetailsUnit).isNotNull();
		assertThat(homeInsuranceCovaregeAttibutesDetailsUnit.getCode()).isEqualTo(coverageAttributesDetailsUnit.getCode());
		assertThat(homeInsuranceCovaregeAttibutesDetailsUnit.getDescription()).isEqualTo(coverageAttributesDetailsUnit.getDescription());
	}

	private void assertHomeInsuranceProduct(final ProductDomain productDomain, final HomeInsuranceProduct homeInsuranceProduct) {
		assertThat(homeInsuranceProduct).isNotNull();
		assertThat(homeInsuranceProduct.getAdditional().get(0).getValue()).isEqualTo(productDomain.getAdditional().get(0));
		assertThat(homeInsuranceProduct.getProtective()).isEqualTo(productDomain.getProtective());
		assertThat(homeInsuranceProduct.getCode()).isEqualTo(productDomain.getCode());
		assertThat(homeInsuranceProduct.getTargetAudiences().get(0).getValue()).isEqualTo(productDomain.getTargetAudiences().get(0));

		assertThat(homeInsuranceProduct.getCustomerServices()).isNotEmpty();
		assertThat(homeInsuranceProduct.getCustomerServices().size()).isEqualTo(1);
		assertCustomerService(homeInsuranceProduct.getCustomerServices(), productDomain.getCustomerServices());

		assertThat(homeInsuranceProduct.getCoverages()).isNotEmpty();
		assertThat(homeInsuranceProduct.getCoverages().size()).isEqualTo(2);
		assertCoverageItem(homeInsuranceProduct.getCoverages().get(0), productDomain.getCoverages().get(0));
		assertCoverageItem(homeInsuranceProduct.getCoverages().get(1), productDomain.getCoverages().get(1));

		assertThat(homeInsuranceProduct.getValidity().size()).isEqualTo(1);
		assertValidity(homeInsuranceProduct.getValidity().get(0), productDomain.getValidity().get(0));

		assertThat(homeInsuranceProduct.getTermsAndConditions()).isNotEmpty();
		assertThat(homeInsuranceProduct.getTermsAndConditions().size()).isEqualTo(1);
		assertTermsAndConditions(homeInsuranceProduct.getTermsAndConditions().get(0), productDomain.getTermsAndConditions().get(0));

		assertThat(homeInsuranceProduct.getPremiumPayments()).isNotEmpty();
		assertThat(homeInsuranceProduct.getPremiumPayments().size()).isEqualTo(1);
		assertPremiumPayment(homeInsuranceProduct.getPremiumPayments().get(0), productDomain.getPremiumPayments().get(0));

		assertThat(homeInsuranceProduct.getMinimumRequirements()).isNotEmpty();
		assertMinimumRequirements(homeInsuranceProduct.getMinimumRequirements().get(0), productDomain.getMinimumRequirements().get(0));

		assertThat(homeInsuranceProduct.getPremiumRates())
						.isNotEmpty()
						.containsExactlyInAnyOrderElementsOf(productDomain.getPremiumRates());
	}

	private void assertMinimumRequirements(final HomeInsuranceMinimumRequirements homeInsuranceMinimumRequirement, final MinimumRequirement minimumRequirement) {
		assertThat(homeInsuranceMinimumRequirement.getContractingMinRequirement()).isEqualTo(minimumRequirement.getContractingMinRequirement());
		assertThat(homeInsuranceMinimumRequirement.getContractingType().getValue()).isEqualTo(minimumRequirement.getContractingType());
	}

	private void assertPremiumPayment(final HomeInsurancePremiumPayment homeInsurancePremiumPayment, final PremiumPayment premiumPayment) {
		assertThat(homeInsurancePremiumPayment.getPaymentMethod().getValue()).isEqualTo(premiumPayment.getPaymentMethod());
		assertThat(homeInsurancePremiumPayment.getPaymentType().getValue()).isEqualTo(premiumPayment.getPaymentType());
		assertThat(homeInsurancePremiumPayment.getPaymentMethodDetail()).isEqualTo(premiumPayment.getPaymentMethodDetail());
	}

	private void assertTermsAndConditions(final HomeInsuranceTermsAndConditions homeInsuranceTermsAndCondition,
																				final TermsAndConditions termsAndCondition) {
		assertThat(homeInsuranceTermsAndCondition.getDefinition()).isEqualTo(termsAndCondition.getDefinition());
		assertThat(homeInsuranceTermsAndCondition.getSusepProcessNumber()).isEqualTo(termsAndCondition.getSusepProcessNumber());
	}

	private void assertCustomerService(final List<HomeInsuranceProduct.CustomerServicesEnum> homeInsuranceCustomerService, final List<String> customerServices) {
		final List<String> expected = homeInsuranceCustomerService.stream()
						.map(HomeInsuranceProduct.CustomerServicesEnum::getValue).collect(Collectors.toList());
		assertThat(expected).containsExactlyInAnyOrderElementsOf(customerServices);
	}

	private void assertCoverageItem(final HomeInsuranceCoverages homeInsuranceCoverage, final Coverages coverage) {
		assertThat(coverage.getCoverageType())
						.isEqualTo(homeInsuranceCoverage.getCoverageType().getValue());
		assertThat(coverage.getCoverageDetail()).isEqualTo(homeInsuranceCoverage.getCoverageDetail());
		assertThat(coverage.getCoveragePermissionSeparateAcquisition())
						.isEqualTo(homeInsuranceCoverage.getCoveragePermissionSeparteAquisition());
	}

	private void assertValidity(final HomeInsuranceValidity validity, final Validity expectedValidity) {
		assertThat(expectedValidity.getTerm()).isEqualTo(validity.getTerm().getValue());
		assertThat(expectedValidity.getTermOthers()).isEqualTo(validity.getTermOthers());
	}

	private void assertHomeInsuranceAssistanceServices(final List<ComplementaryAssistanceService> assistanceServices,
																										 final List<HomeInsuranceAssistanceServices> homeInsuranceAssistanceServices) {

		assertThat(assistanceServices).isNotEmpty();
		assertThat(homeInsuranceAssistanceServices).isNotEmpty();

		final HomeInsuranceAssistanceServices homeInsuranceAssistanceService = homeInsuranceAssistanceServices.get(0);
		final ComplementaryAssistanceService complementaryAssistanceService = assistanceServices.get(0);

		assertThat(homeInsuranceAssistanceService.getComplementaryAssistanceServicesDetail()).isEqualTo(complementaryAssistanceService.getAssistanceServicesDetail());
		assertThat(homeInsuranceAssistanceService.getAssistanceServicesPackage().getValue())
						.isEqualTo(complementaryAssistanceService.getAssistanceServicesPackage());
		assertThat(homeInsuranceAssistanceService.getChargeTypeSignaling().getValue())
						.isEqualTo(complementaryAssistanceService.getChargeTypeSignaling());
	}

	private void assertHomeInsurancePropertyCharacteristics(final List<PropertyCharacteristics> propertyCharacteristics,
															final List<HomeInsurancePropertyCharacteristics> homeInsuranceAssistanceServices) {
		assertThat(propertyCharacteristics).isNotEmpty();
		assertThat(homeInsuranceAssistanceServices).isNotEmpty();

		final HomeInsurancePropertyCharacteristics homeInsurancePropertyCharacteristic = homeInsuranceAssistanceServices.get(0);
		final PropertyCharacteristics characteristics = propertyCharacteristics.get(0);

		assertThat(homeInsurancePropertyCharacteristic.getPropertyType().getValue())
						.isNotNull()
						.isEqualTo(characteristics.getPropertyType());
		assertThat(homeInsurancePropertyCharacteristic.getPropertyBuildType().getValue())
						.isNotNull()
						.isEqualTo(characteristics.getPropertyBuildType());
		assertThat(homeInsurancePropertyCharacteristic.getPropertyUsageType().getValue())
						.isNotNull()
						.isEqualTo(characteristics.getPropertyUsageType());
		assertThat(homeInsurancePropertyCharacteristic.getDestinationInsuredImportance().getValue())
						.isNotNull()
						.isEqualTo(characteristics.getDestinationInsuredImportance());
	}
}