package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.common.HomeInsuranceTestUtil;
import br.com.bradescoseguros.opin.domain.residential.ResidentialDomain;
import br.com.bradescoseguros.opin.dummy.DummyObjectsUtil;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceBrand;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceCompany;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceProduct;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceListData;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(MockitoExtension.class)
class ResidentialMapperTest {

	@Test
	void mapResponseHomeInsuranceListDataFrom_withEmptyResidentialDomainList_shouldReturnHomeInsuranceListData() {
		//Arrange
		final String propertyZipCode = "12345678";

		//Act
		final ResponseHomeInsuranceListData responseHomeInsuranceListData = ResidentialMapper.INSTANCE.mapResponseHomeInsuranceListDataFrom(null, propertyZipCode);

		//Asserts
		assertThat(responseHomeInsuranceListData).isNotNull();
		assertThat(responseHomeInsuranceListData.getBrand()).isNull();
	}

	@Test
	void mapResponseHomeInsuranceListDataFrom_withResidentialDomainList_shouldMapResponseHomeInsuranceListData() {

		//Arrange

		final String propertyZipCode = "12345678";
		var residentialDomains = Arrays.asList(HomeInsuranceTestUtil.getResidentialDomain(),
						HomeInsuranceTestUtil.getResidentialDomain(),
						HomeInsuranceTestUtil.getResidentialDomain());
		var residential = residentialDomains.get(0);

		//Act
		final ResponseHomeInsuranceListData responseHomeInsuranceListData = ResidentialMapper.INSTANCE.mapResponseHomeInsuranceListDataFrom(residentialDomains, propertyZipCode);

		//Asserts
		assertThat(responseHomeInsuranceListData).isNotNull();
		assertThat(responseHomeInsuranceListData.getBrand().getName()).isEqualTo(residential.getBrandName());
		assertThat(responseHomeInsuranceListData.getBrand().getCompany()).isNotNull().isNotEmpty();

		final HomeInsuranceCompany company = responseHomeInsuranceListData.getBrand().getCompany().get(0);
		assertThat(company.getName()).isEqualTo(residential.getCompanyName());
		assertThat(company.getCnpjNumber()).isEqualTo(residential.getCnpjNumber());
		assertThat(company.getProducts()).isNotNull().isNotEmpty();
		assertThat(company.getProducts().size()).isEqualTo(residentialDomains.size());
		assertTrue(company.getProducts().stream().allMatch(item -> item.getPropertyZipCode().equals(propertyZipCode)));
	}

	@Test
	@Tag("unit")
	void mapHomeInsuranceBrandFrom_withResidentialDomain_shouldReturnHomeInsuranceBrand() {

		//Arrange
		final ResidentialDomain residentialDomain = HomeInsuranceTestUtil.getResidentialDomain();

		//Act
		final HomeInsuranceBrand homeInsuranceBrand = ResidentialMapper.INSTANCE.mapHomeInsuranceBrandFrom(residentialDomain);

		//Asserts
		assertThat(homeInsuranceBrand).isNotNull();
		assertThat(homeInsuranceBrand.getName()).isNotNull().isEqualTo(residentialDomain.getBrandName());

	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceBrandFrom_withNullResidentialDomain_shouldReturnNull() {

		//Act
		assertThat(ResidentialMapper.INSTANCE.mapHomeInsuranceBrandFrom(null)).isNull();
	}

	@Test
	@Tag("unit")
	void mapHomeInsuranceCompanyFrom_withResidentialDomain_shouldReturnHomeInsuranceCompany() {

		//Arrange
		final ResidentialDomain residentialDomain = HomeInsuranceTestUtil.getResidentialDomain();
		final List<HomeInsuranceProduct> productList = List.of(DummyObjectsUtil.newInstance(HomeInsuranceProduct.class));

		//Act
		final List<HomeInsuranceCompany> homeInsuranceCompany = ResidentialMapper.INSTANCE.mapHomeInsuranceCompanyFrom(residentialDomain, productList);

		//Asserts
		assertThat(homeInsuranceCompany).isNotEmpty();
		assertHomeInsuranceCompany(homeInsuranceCompany.get(0), residentialDomain);
	}

	@Test
	@Tag("mutation")
	void mapHomeInsuranceCompanyFrom_withNullResidentialDomain_shouldReturnNull() {

		//Act
		assertThat(ResidentialMapper.INSTANCE.mapHomeInsuranceCompanyFrom(null, new ArrayList<>())).isEmpty();
	}

	private void assertHomeInsuranceCompany(final HomeInsuranceCompany company, final ResidentialDomain residentialDomain) {
		assertThat(company).isNotNull();
		assertThat(company.getName()).isEqualTo(residentialDomain.getCompanyName());
		assertThat(company.getCnpjNumber()).isEqualTo(residentialDomain.getCnpjNumber());
	}

}