package br.com.bradescoseguros.opin.interfaceadapter.autogenerated.delegate;

import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceList;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
class HomeInsuranceApiTest {

	private InnerHomeInsuranceApi homeInsuranceApi = new InnerHomeInsuranceApi();

	@Test
	void getDelegate_whenCalled_shouldReturnAHomeInsuranceApiDelegateInstance() {
		assertThat(homeInsuranceApi.getDelegate()).isNotNull();
	}

	@Test
	void getResidentialInsurance_withParameters_shouldReturnResponseEntity() {

		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = homeInsuranceApi.getResidentialInsurance("cacheControl",
						"commercializationArea",
						"contententSecurityPollicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"xFrameOptions",
						10,
						10);

		assertThat(residentialInsurance).isNotNull();
	}

	public class InnerHomeInsuranceApi implements HomeInsuranceApi {
		@Override
		public HomeInsuranceApiDelegate getDelegate() {
			return HomeInsuranceApi.super.getDelegate();
		}

		@Override
		public ResponseEntity<ResponseHomeInsuranceList> getResidentialInsurance(String cacheControl, String commercializationArea, String contentSecurityPolicy, String contentType, String strictTransportSecurity, String xContentTypeOptions, String xFrameOptions, Integer page, Integer pageSize) {
			return HomeInsuranceApi.super.getResidentialInsurance(cacheControl, commercializationArea, contentSecurityPolicy, contentType, strictTransportSecurity, xContentTypeOptions, xFrameOptions, page, pageSize);
		}
	}
}