package br.com.bradescoseguros.opin.interfaceadapter.autogenerated.delegate;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
class HomeInsuranceApiControllerTest {

	@InjectMocks
	private HomeInsuranceApiController homeInsuranceApiController;

	@Test
	void getDelegate_whenIsCalled_shouldReturnAHomeInsuranceApiDelegateInstance() {
		assertThat(homeInsuranceApiController.getDelegate()).isNotNull();
	}

}