package br.com.bradescoseguros.opin.interfaceadapter.autogenerated.delegate;

import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceList;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.context.request.NativeWebRequest;

import javax.servlet.http.HttpServletResponse;
import java.io.PrintWriter;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class HomeInsuranceApiDelegateTest {

	@Mock
	private NativeWebRequest mockNativeWebRequest;

	@Mock
	private HttpServletResponse mockHttpServletResponse;

	@Mock
	private PrintWriter mockPrintWriter;

	private InnerHomeInsuranceDelegate innerHomeInsuranceDelegate;

	@BeforeEach
	void setup() {
		innerHomeInsuranceDelegate = new InnerHomeInsuranceDelegate(mockNativeWebRequest);
	}

	@Test
	@SneakyThrows
	void getResidentialInsurance_whenMediaTypeIsApplicationJson_shouldReturnResponse() {

		setupWebRequestProperties(MediaType.APPLICATION_JSON_VALUE);

		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = innerHomeInsuranceDelegate.getResidentialInsurance("cacheControl",
						"commercializationArea",
						"contentSecurityPolicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"xFrameOptions",
						1,
						10);

		assertThat(residentialInsurance).isNotNull();
		assertThat(residentialInsurance.getStatusCode())
						.isNotNull()
						.isEqualTo(HttpStatus.NOT_IMPLEMENTED);
		verify(mockHttpServletResponse).getWriter();
	}

	@Test
	@SneakyThrows
	void getResidentialInsurance_whenMediaTypeIsApplicationJsonWithCharset_shouldReturnResponse() {

		setupWebRequestProperties("application/json;charset=utf-8");

		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = innerHomeInsuranceDelegate.getResidentialInsurance("cacheControl",
						"commercializationArea",
						"contentSecurityPolicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"xFrameOptions",
						1,
						10);

		assertThat(residentialInsurance).isNotNull();
		assertThat(residentialInsurance.getStatusCode())
						.isNotNull()
						.isEqualTo(HttpStatus.NOT_IMPLEMENTED);
		verify(mockHttpServletResponse).getWriter();
	}

	@Test
	@SneakyThrows
	void getResidentialInsurance_whenMediaTypeIsInvalid_shouldReturnResponse() {

		when(mockNativeWebRequest.getHeader("Accept")).thenReturn(MediaType.APPLICATION_XML_VALUE);

		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = innerHomeInsuranceDelegate.getResidentialInsurance("cacheControl",
						"commercializationArea",
						"contentSecurityPolicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"xFrameOptions",
						1,
						10);

		assertThat(residentialInsurance).isNotNull();
		assertThat(residentialInsurance.getStatusCode())
						.isNotNull()
						.isEqualTo(HttpStatus.NOT_IMPLEMENTED);
		verify(mockHttpServletResponse, never()).getWriter();
	}

	@SneakyThrows
	private void setupWebRequestProperties(final String applicationJsonValue) {
		when(mockNativeWebRequest.getHeader("Accept")).thenReturn(applicationJsonValue);
		when(mockNativeWebRequest.getNativeResponse(any())).thenReturn(mockHttpServletResponse);
		when(mockHttpServletResponse.getWriter()).thenReturn(mockPrintWriter);
	}

	@RequiredArgsConstructor
	public class InnerHomeInsuranceDelegate implements HomeInsuranceApiDelegate {

		private final NativeWebRequest nativeWebRequest;

		@Override
		public Optional<NativeWebRequest> getRequest() {
			return Optional.of(nativeWebRequest);
		}

		@Override
		public ResponseEntity<ResponseHomeInsuranceList> getResidentialInsurance(String cacheControl,
																																						 String commercializationArea,
																																						 String contentSecurityPolicy,
																																						 String contentType,
																																						 String strictTransportSecurity,
																																						 String xContentTypeOptions,
																																						 String xFrameOptions,
																																						 Integer page,
																																						 Integer pageSize) {

			return HomeInsuranceApiDelegate.super.getResidentialInsurance(cacheControl,
							commercializationArea,
							contentSecurityPolicy,
							contentType,
							strictTransportSecurity,
							xContentTypeOptions,
							xFrameOptions,
							page,
							pageSize);
		}
	}
}