package br.com.bradescoseguros.opin.interfaceadapter.delegate;


import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.Links;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.Meta;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.IanaLinkRelations;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedModel;
import org.springframework.web.util.UriComponentsBuilder;

import java.util.Optional;

public abstract class BasePagedDelegate<T> {

    private static final String HTTPS = "https";

    private PagedResourcesAssembler<T> pagedResourcesAssembler;
    @Value("${gateway.host:#{null}}")
    private String gatewayHost;
    @Value("${gateway.port:#{null}}")
    private String gatewayPort;

    @Autowired
    public void setPagedResourcesAssembler(final PagedResourcesAssembler<T> pagedResourcesAssembler) {
        this.pagedResourcesAssembler = pagedResourcesAssembler;
    }

    protected Meta buildResponseMeta(final Page<T> pagedCollection) {
        return Meta.builder()
                .totalRecords(pagedCollection.getNumberOfElements())
                .totalPages(pagedCollection.getTotalPages())
                .build();
    }

    protected Links buildResponseLinks(final Page<T> pagedCollection) {
        final PagedModel<EntityModel<T>> pagedModel = pagedResourcesAssembler.toModel(pagedCollection);
        return Links.builder()
                .self(getLink(pagedModel.getLink(IanaLinkRelations.SELF)))
                .first(getLink(pagedModel.getLink(IanaLinkRelations.FIRST)))
                .next(getLink(pagedModel.getNextLink()))
                .prev(getLink(pagedModel.getPreviousLink()))
                .last(getLink(pagedModel.getLink(IanaLinkRelations.LAST)))
                .build();
    }

    protected Pageable getPageable(final Integer page, final Integer pageSize) {
        return PageRequest.of(page - 1, pageSize);
    }

    private String getLink(final Optional<Link> link) {
        String returnLink = link.map(Link::getHref).orElse("");
        if (link.isPresent() && StringUtils.isNotEmpty(this.gatewayHost)) {
            var builder = UriComponentsBuilder.fromHttpUrl(link.get().getHref());
            returnLink = builder.scheme(HTTPS).host(this.gatewayHost).port(this.gatewayPort).build().toUriString();
        }
        return returnLink;
    }
}