package br.com.bradescoseguros.opin.interfaceadapter.delegate;

import br.com.bradescoseguros.opin.businessrule.usecase.homeinsurance.HomeInsuranceUseCase;
import br.com.bradescoseguros.opin.domain.residential.ResidentialDomain;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.delegate.HomeInsuranceApiDelegate;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceList;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceListData;
import br.com.bradescoseguros.opin.interfaceadapter.mapper.ResidentialMapper;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

@Service
@AllArgsConstructor
@Slf4j
public class HomeInsuranceApiDelegateImpl extends BasePagedDelegate<ResidentialDomain> implements HomeInsuranceApiDelegate {

    private final HomeInsuranceUseCase homeInsuranceUseCase;

    @Override
    public ResponseEntity<ResponseHomeInsuranceList> getResidentialInsurance(String cacheControl,
                                                                             String commercializationArea,
                                                                             String contentSecurityPolicy,
                                                                             String contentType,
                                                                             String strictTransportSecurity,
                                                                             String xContentTypeOptions,
                                                                             String xFrameOptions,
                                                                             Integer page, Integer pageSize) {
        log.info("Init 'Find all Products' params values for 'page' = " + page + " and size = " + pageSize);
        final Page<ResidentialDomain> residentialProductsPage = homeInsuranceUseCase.getResidentialInsuranceProducts(getPageable(page, pageSize), commercializationArea);

        var responseHomeInsuranceListData = ResidentialMapper.INSTANCE.mapResponseHomeInsuranceListDataFrom(residentialProductsPage.getContent(), commercializationArea);

        return buildResponseEntity(responseHomeInsuranceListData, residentialProductsPage);
    }

    private ResponseEntity<ResponseHomeInsuranceList> buildResponseEntity(final ResponseHomeInsuranceListData responseHomeInsuranceListData, final Page<ResidentialDomain> residentialProductsPage) {
        return new ResponseEntity<>(ResponseHomeInsuranceList.builder()
                .meta(this.buildResponseMeta(residentialProductsPage))
                .links(this.buildResponseLinks(residentialProductsPage))
                .data(responseHomeInsuranceListData)
                .build(), null, HttpStatus.OK);
    }
}