package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;
import br.com.bradescoseguros.opin.interfaceadapter.util.EnumUtil;
import br.com.bradescoseguros.opin.interfaceadapter.util.NumberUtil;
import org.mapstruct.Mapper;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface CommonMappings {

	CommonMappings INSTANCE = Mappers.getMapper(CommonMappings.class);

	@Named("mapAttributesDetailsAmountFrom")
	default BigDecimal mapAttributesDetailsAmountFrom(final BigDecimal amount) {
		return NumberUtil.formatBigDecimalNumber(amount);
	}

	@Named("mapCoverageTypeFrom")
	default HomeInsuranceCoverages.CoverageTypeEnum mapCoverageTypeFrom(final String type) {
		return (HomeInsuranceCoverages.CoverageTypeEnum) EnumUtil.getEnumValue(HomeInsuranceCoverages.CoverageTypeEnum.class, type);
	}

	@Named("mapAdditionalEnumFrom")
	default HomeInsuranceProduct.AdditionalEnum mapAdditionalEnumFrom(final String type) {
		return (HomeInsuranceProduct.AdditionalEnum) EnumUtil.getEnumValue(HomeInsuranceProduct.AdditionalEnum.class, type);
	}

	@Named("mapCustomerServicesEnumFrom")
	default List<HomeInsuranceProduct.CustomerServicesEnum> mapCustomerServicesEnumFrom(final List<String> values) {
		return values.stream()
						.map(value -> (HomeInsuranceProduct.CustomerServicesEnum) EnumUtil.getEnumValue(HomeInsuranceProduct.CustomerServicesEnum.class, value))
						.collect(Collectors.toList());
	}

	@Named("mapTargetAudienceFrom")
	default List<HomeInsuranceProduct.TargetAudiencesEnum> mapTargetAudienceFrom(final List<String> targetAudiences) {

		return targetAudiences.stream()
				.map(ta -> (HomeInsuranceProduct.TargetAudiencesEnum) EnumUtil.getEnumValue(HomeInsuranceProduct.TargetAudiencesEnum.class, ta))
				.collect(Collectors.toList());
	}

	@Named("mapAssistanceServicesPackageEnumFrom")
	default HomeInsuranceAssistanceServices.AssistanceServicesPackageEnum mapAssistanceServicesPackageEnumFrom(final String value) {
		return (HomeInsuranceAssistanceServices.AssistanceServicesPackageEnum) EnumUtil.getEnumValue(HomeInsuranceAssistanceServices.AssistanceServicesPackageEnum.class, value);
	}

	@Named("mapChargeTypeSignalingEnumFrom")
	default HomeInsuranceAssistanceServices.ChargeTypeSignalingEnum mapChargeTypeSignalingEnumFrom(final String value) {
		return (HomeInsuranceAssistanceServices.ChargeTypeSignalingEnum) EnumUtil.getEnumValue(HomeInsuranceAssistanceServices.ChargeTypeSignalingEnum.class, value);
	}

	@Named("mapPropertyUsageTypeEnumFrom")
	default HomeInsurancePropertyCharacteristics.PropertyUsageTypeEnum mapPropertyUsageTypeEnumFrom(final String value) {
		return (HomeInsurancePropertyCharacteristics.PropertyUsageTypeEnum) EnumUtil.getEnumValue(HomeInsurancePropertyCharacteristics.PropertyUsageTypeEnum.class, value);
	}

	@Named("mapPropertyBuildTypeEnumFrom")
	default HomeInsurancePropertyCharacteristics.PropertyBuildTypeEnum mapPropertyBuildTypeEnumFrom(final String value) {
		return (HomeInsurancePropertyCharacteristics.PropertyBuildTypeEnum) EnumUtil.getEnumValue(HomeInsurancePropertyCharacteristics.PropertyBuildTypeEnum.class, value);
	}

	@Named("mapPropertyTypeEnumFrom")
	default HomeInsurancePropertyCharacteristics.PropertyTypeEnum mapPropertyTypeEnumFrom(final String value) {
		return (HomeInsurancePropertyCharacteristics.PropertyTypeEnum) EnumUtil.getEnumValue(HomeInsurancePropertyCharacteristics.PropertyTypeEnum.class, value);
	}

	@Named("mapDestinationInsuredImportanceEnum")
	default HomeInsurancePropertyCharacteristics.DestinationInsuredImportanceEnum mapDestinationInsuredImportanceEnum(final String value) {
		return (HomeInsurancePropertyCharacteristics.DestinationInsuredImportanceEnum) EnumUtil.getEnumValue(HomeInsurancePropertyCharacteristics.DestinationInsuredImportanceEnum.class, value);
	}

	@Named("mapPaymentMethodEnumFrom")
	default HomeInsurancePremiumPayment.PaymentMethodEnum mapPaymentMethodEnumFrom(final String value) {
		return (HomeInsurancePremiumPayment.PaymentMethodEnum) EnumUtil.getEnumValue(HomeInsurancePremiumPayment.PaymentMethodEnum.class, value);
	}

	@Named("mapPaymentTypeEnumFrom")
	default HomeInsurancePremiumPayment.PaymentTypeEnum mapPaymentTypeEnumFrom(final String value) {
		return (HomeInsurancePremiumPayment.PaymentTypeEnum) EnumUtil.getEnumValue(HomeInsurancePremiumPayment.PaymentTypeEnum.class, value);
	}

	@Named("mapTermEnumFrom")
	default HomeInsuranceValidity.TermEnum mapTermEnumFrom(final String value) {
		return (HomeInsuranceValidity.TermEnum) EnumUtil.getEnumValue(HomeInsuranceValidity.TermEnum.class, value);
	}

	@Named("mapContractingTypeFrom")
	default HomeInsuranceMinimumRequirements.ContractingTypeEnum mapContractingTypeFrom(final String value) {
		return (HomeInsuranceMinimumRequirements.ContractingTypeEnum) EnumUtil.getEnumValue(HomeInsuranceMinimumRequirements.ContractingTypeEnum.class, value);
	}
}