package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.domain.residential.*;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, uses = {CommonMappings.class})
public interface ProductMapper {

	ProductMapper INSTANCE = Mappers.getMapper(ProductMapper.class);

	@Named("mapHomeInsuranceProductFrom")
	@Mapping(target = "coverages", source = "coverages", qualifiedByName = "mapCoveragesFrom")
	@Mapping(target = "additional", source = "additional", qualifiedByName = "mapAdditionalEnumItemsFrom")
	@Mapping(target = "customerServices", source = "customerServices", qualifiedByName = "mapCustomerServicesEnumFrom")
	@Mapping(target = "targetAudiences", source = "targetAudiences", qualifiedByName = "mapTargetAudienceFrom")
	@Mapping(target = "assistanceServices", source = "assistanceServices", qualifiedByName = "mapHomeInsuranceAssistanceServicesFrom")
	@Mapping(target = "propertyCharacteristics", source = "propertyCharacteristics", qualifiedByName = "mapPropertyCharacteristicsFrom")
	@Mapping(target = "validity", source = "validity", qualifiedByName = "mapValidityFrom")
	@Mapping(target = "minimumRequirements", source = "minimumRequirements", qualifiedByName = "mapMinimumRequirementsItemsFrom")
	@Mapping(target = "premiumPayments", source = "premiumPayments", qualifiedByName = "mapPremiumPaymentsFrom")
	HomeInsuranceProduct mapHomeInsuranceProductFrom(final ProductDomain productDomain);

	@Named("mapHomeInsuranceCoveragesFrom")
	@Mapping(target = "coverageAttributes", source = "coverageAttributes", qualifiedByName = "mapCoverageAttributes")
	@Mapping(target = "coverageType", source = "coverageType", qualifiedByName = "mapCoverageTypeFrom")
	@Mapping(target = "coveragePermissionSeparteAquisition", source = "coveragePermissionSeparateAcquisition")
	HomeInsuranceCoverages mapHomeInsuranceCoveragesFrom(final Coverages coverages);

	@Named("mapCoverageAttributes")
	@Mapping(target = "minLMI", source = "minLMI", qualifiedByName = "mapCoverageAttributesDetails")
	@Mapping(target = "maxLMI", source = "maxLMI", qualifiedByName = "mapCoverageAttributesDetails")
	@Mapping(target = "minDeductibleAmount", source = "minDeductibleAmount", qualifiedByName = "mapCoverageAttributesDetails")
	HomeInsuranceCoverageAttributes mapCoverageAttributes(final CoverageAttributes coverageAttributes);

	@Named("mapCoverageAttributesDetails")
	@Mapping(target = "amount", source = "amount", qualifiedByName = "mapAttributesDetailsAmountFrom")
	@Mapping(target = "unit", source = "unit", qualifiedByName = "mapHomeInsuranceCoverageAttributesDetailsUnit")
	HomeInsuranceCovaregeAttibutesDetails mapCoverageAttributesDetails(final CoverageAttributesDetails coverageAttributesDetails);

	@Named("mapHomeInsuranceCoverageAttributesDetailsUnit")
	HomeInsuranceCovaregeAttibutesDetailsUnit mapHomeInsuranceCoverageAttributesDetailsUnit(final CoverageAttributesDetailsUnit unit);

	@Named("mapCoveragesFrom")
	default List<HomeInsuranceCoverages> mapCoveragesFrom(final List<Coverages> coverages) {
		final List<HomeInsuranceCoverages> homeInsuranceCoverages = new ArrayList<>();
		coverages.forEach(coverage -> homeInsuranceCoverages.add(mapHomeInsuranceCoveragesFrom(coverage)));
		return homeInsuranceCoverages;
	}

	@Named("mapHomeInsuranceAssistanceServicesFrom")
	default List<HomeInsuranceAssistanceServices> mapHomeInsuranceAssistanceServicesFrom(final List<ComplementaryAssistanceService> assistanceServices) {

		if (assistanceServices == null) {
			return Collections.emptyList();
		}

		final List<HomeInsuranceAssistanceServices> response = new ArrayList<>();

		assistanceServices
						.forEach(assistanceService -> response.add(mapAssistanceServiceFrom(assistanceService)));

		return response;
	}

	@Named("mapAssistanceServiceFrom")
	@Mapping(target = "assistanceServicesPackage", source = "assistanceServicesPackage", qualifiedByName = "mapAssistanceServicesPackageEnumFrom")
	@Mapping(target = "chargeTypeSignaling", source = "chargeTypeSignaling", qualifiedByName = "mapChargeTypeSignalingEnumFrom")
	@Mapping(target = "complementaryAssistanceServicesDetail", source = "assistanceServicesDetail")
	HomeInsuranceAssistanceServices mapAssistanceServiceFrom(final ComplementaryAssistanceService complementaryAssistanceService);

	@Named("mapPropertyCharacteristicsFrom")
	default List<HomeInsurancePropertyCharacteristics> mapPropertyCharacteristicsFrom(List<PropertyCharacteristics> propertiesCharacteristics) {

		if (propertiesCharacteristics == null) {
			return Collections.emptyList();
		}

		final List<HomeInsurancePropertyCharacteristics> response = new ArrayList<>();

		propertiesCharacteristics
						.forEach(propertyCharacteristic -> response.add(mapPropertyCharacteristic(propertyCharacteristic)));
		return response;
	}

	@Named("mapPropertyCharacteristic")
	@Mapping(target = "propertyType", source = "propertyType", qualifiedByName = "mapPropertyTypeEnumFrom")
	@Mapping(target = "propertyBuildType", source = "propertyBuildType", qualifiedByName = "mapPropertyBuildTypeEnumFrom")
	@Mapping(target = "propertyUsageType", source = "propertyUsageType", qualifiedByName = "mapPropertyUsageTypeEnumFrom")
	@Mapping(target = "destinationInsuredImportance", source = "destinationInsuredImportance", qualifiedByName = "mapDestinationInsuredImportanceEnum")
	HomeInsurancePropertyCharacteristics mapPropertyCharacteristic(final PropertyCharacteristics propertyCharacteristic);

  @Named("mapPremiumPaymentsFrom")
	default List<HomeInsurancePremiumPayment> mapPremiumPaymentsFrom(final List<PremiumPayment> premiumPayments) {

		if (premiumPayments == null) {
			return Collections.emptyList();
		}

		final List<HomeInsurancePremiumPayment> response = new ArrayList<>();

		premiumPayments
						.forEach(premiumPayment -> response.add(mapPremiumPayment(premiumPayment)));

		return response;
	}

	@Named("mapPremiumPayment")
	@Mapping(target = "paymentMethod", source = "paymentMethod", qualifiedByName = "mapPaymentMethodEnumFrom")
	@Mapping(target = "paymentType", source = "paymentType", qualifiedByName = "mapPaymentTypeEnumFrom")
	HomeInsurancePremiumPayment mapPremiumPayment(final PremiumPayment premiumPayment);

	@Named("mapValidityFrom")
	default List<HomeInsuranceValidity> mapValidityFrom(final List<Validity> validities) {

		if (validities == null) {
			return Collections.emptyList();
		}

		final List<HomeInsuranceValidity> response = new ArrayList<>();

		validities
						.forEach(validity -> response.add(mapValidityItemFrom(validity)));

		return response;
	}

	@Named("mapValidityItemFrom")
	@Mapping(target = "term", source = "term", qualifiedByName = "mapTermEnumFrom")
	HomeInsuranceValidity mapValidityItemFrom(Validity validity);

	@Named("mapMinimumRequirementsItemsFrom")
	default List<HomeInsuranceMinimumRequirements> mapMinimumRequirementsItemsFrom(final List<MinimumRequirement> minimumRequirements) {

		if (minimumRequirements == null) {
			return Collections.emptyList();
		}

		final List<HomeInsuranceMinimumRequirements> response = new ArrayList<>();

		minimumRequirements.forEach(requirements -> response.add(mapMinimumRequirements(requirements)));

		return response;
	}

	@Named("mapMinimumRequirements")
	@Mapping(target = "contractingType", source = "contractingType", qualifiedByName = "mapContractingTypeFrom")
	HomeInsuranceMinimumRequirements mapMinimumRequirements(final MinimumRequirement minimumRequirement);

	@Named("mapAdditionalEnumItemsFrom")
	default List<HomeInsuranceProduct.AdditionalEnum> mapAdditionalEnumItemsFrom(final List<String> additionals) {

		if (additionals == null) {
			return Collections.emptyList();
		}

		final List<HomeInsuranceProduct.AdditionalEnum> response = new ArrayList<>();

		additionals.forEach(additional -> response.add(CommonMappings.INSTANCE.mapAdditionalEnumFrom(additional)));

		return response;
	}
}