package br.com.bradescoseguros.opin.interfaceadapter.mapper;

import br.com.bradescoseguros.opin.domain.residential.ResidentialDomain;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceBrand;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceCompany;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.HomeInsuranceProduct;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.ResponseHomeInsuranceListData;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface ResidentialMapper {

	ResidentialMapper INSTANCE = Mappers.getMapper(ResidentialMapper.class);

	@Named("mapResponseHomeInsuranceListDataFrom")
	default ResponseHomeInsuranceListData mapResponseHomeInsuranceListDataFrom(final List<ResidentialDomain> residentialDomains, final String propertyZipCode) {

		if (residentialDomains == null) {
			return new ResponseHomeInsuranceListData();
		}

		final List<HomeInsuranceProduct> products = new ArrayList<>();

		residentialDomains
						.forEach(residentialDomain -> {
							var homeInsuranceProduct = ProductMapper.INSTANCE.mapHomeInsuranceProductFrom(residentialDomain.getProduct());
							homeInsuranceProduct.setPropertyZipCode(propertyZipCode);
							products.add(homeInsuranceProduct);
						});


		final ResidentialDomain residential = residentialDomains.get(0);

		final List<HomeInsuranceCompany> companies = mapHomeInsuranceCompanyFrom(residential, products);

		var homeInsuranceBrand = HomeInsuranceBrand.builder()
						.name(residential.getBrandName())
						.company(companies)
						.build();

		return ResponseHomeInsuranceListData
						.builder()
						.brand(homeInsuranceBrand)
						.build();
	}

	@Mapping(target = "name", source = "brandName")
	HomeInsuranceBrand mapHomeInsuranceBrandFrom(final ResidentialDomain residentialDomain);

	@Named("mapHomeInsuranceCompanyFrom")
	default List<HomeInsuranceCompany> mapHomeInsuranceCompanyFrom(final ResidentialDomain residentialDomain, final List<HomeInsuranceProduct> products) {

		if (residentialDomain == null) {
			return Collections.emptyList();
		}

		final List<HomeInsuranceCompany> companies = new ArrayList<>();

		companies.add(HomeInsuranceCompany.builder()
					.cnpjNumber(residentialDomain.getCnpjNumber())
					.name(residentialDomain.getCompanyName())
					.products(products)
				.build());

		return companies;
	}
}