package br.com.bradescoseguros.opin.interfaceadapter.delegate;

import br.com.bradescoseguros.opin.businessrule.usecase.homeinsurance.HomeInsuranceUseCase;
import br.com.bradescoseguros.opin.domain.residential.ResidentialDomain;
import br.com.bradescoseguros.opin.dummy.DummyObjectsUtil;
import br.com.bradescoseguros.opin.interfaceadapter.autogenerated.domain.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.hateoas.EntityModel;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class HomeInsuranceApiDelegateImplTest {

	private static final String ZIP_CODE = "1000000";
	private static final String LINK_SELF = "https://api.seguradora.com.br/open-insurance/products-services/v1/home-insurance";

	@Mock
	private HomeInsuranceUseCase mockHomeInsuranceUC;

	@Mock
	private PagedResourcesAssembler<ResidentialDomain> mockPagedResourcesAssembler;

	@InjectMocks
	private HomeInsuranceApiDelegateImpl homeInsuranceApiDelegate;

	private Page<ResidentialDomain> pageResponse;
	private Pageable pageable;

	@BeforeEach
	void setup() {
		homeInsuranceApiDelegate.setPagedResourcesAssembler(mockPagedResourcesAssembler);

		pageResponse = getPageResponse();
		pageable = PageRequest.of(0, 10);

		final EntityModel<ResidentialDomain> firstEntityModel = EntityModel.of(pageResponse.getContent().get(0));
		final EntityModel<ResidentialDomain> secondEntityModel = EntityModel.of(pageResponse.getContent().get(1));

		final PagedModel.PageMetadata pageMetadata = new PagedModel.PageMetadata(1, 2, 2, 1);
		final Link link = Link.of(LINK_SELF);
		final PagedModel<EntityModel<ResidentialDomain>> pagedModel = PagedModel.of(List.of(firstEntityModel, secondEntityModel), pageMetadata, link);

		when(mockPagedResourcesAssembler.toModel(any())).thenReturn(pagedModel);
		when(mockHomeInsuranceUC.getResidentialInsuranceProducts(pageable, ZIP_CODE)).thenReturn(pageResponse);
	}

	@Test
	@Tag("mutation")
	void getResidentialInsurance_withPageableAndZipCode_shouldReturnResponseEntity() {
		//Arrange
		ReflectionTestUtils.setField(homeInsuranceApiDelegate, "gatewayHost", "api.seguradora.com.br");

		//Act
		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = homeInsuranceApiDelegate.getResidentialInsurance("cacheControl",
						ZIP_CODE,
						"contentSecurityPolicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"String xFrameOptions",
						1, 10);

		//Asserts
		assertResidentialInsuranceResponse(residentialInsurance);
	}

	@Test
	@Tag("mutation")
	void getResidentialInsurance_withEmptyGatewayHostAndPageableAndZipCode_shouldReturnResponseEntity() {
		//Arrange
		ReflectionTestUtils.setField(homeInsuranceApiDelegate, "gatewayHost", "");

		//Act
		final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance = homeInsuranceApiDelegate.getResidentialInsurance("cacheControl",
						ZIP_CODE,
						"contentSecurityPolicy",
						"contentType",
						"strictTransportSecurity",
						"xContentTypeOptions",
						"String xFrameOptions",
						1, 10);

		//Asserts
		assertResidentialInsuranceResponse(residentialInsurance);
	}

	private void assertResidentialInsuranceResponse(final ResponseEntity<ResponseHomeInsuranceList> residentialInsurance) {
		assertThat(residentialInsurance.getStatusCode()).isEqualTo(HttpStatus.OK);
		assertThat(residentialInsurance.getBody()).isNotNull();

		final HomeInsuranceBrand homeInsuranceBrand = assertResponseHomeInsuranceListData(residentialInsurance.getBody().getData());
		final ResidentialDomain residentialDomain = pageResponse.getContent().get(0);
		final HomeInsuranceCompany homeInsuranceCompany = assertHomeInsuranceBrand(residentialDomain, homeInsuranceBrand);
		final List<HomeInsuranceProduct> homeInsuranceProducts = assertHomeInsuranceCompany(residentialDomain, homeInsuranceCompany);

		assertThat(homeInsuranceProducts.size()).isEqualTo(pageResponse.getTotalElements());
		assertThat(residentialInsurance.getBody()).isNotNull();
		assertThat(residentialInsurance.getBody().getMeta()).isNotNull();
		assertThat(residentialInsurance.getBody().getLinks()).isNotNull();
		assertThat(residentialInsurance.getBody().getLinks().getSelf()).isNotNull().isEqualTo(LINK_SELF);
		assertThat(residentialInsurance.getBody().getData()).isNotNull();
		verify(mockHomeInsuranceUC).getResidentialInsuranceProducts(pageable, ZIP_CODE);
	}

	private List<HomeInsuranceProduct> assertHomeInsuranceCompany(final ResidentialDomain residentialDomain, final HomeInsuranceCompany company) {
		assertThat(company.getName()).isNotNull().isEqualTo(residentialDomain.getCompanyName());
		assertThat(company.getCnpjNumber()).isNotNull().isEqualTo(residentialDomain.getCnpjNumber());
		assertThat(company.getProducts()).isNotNull().isNotEmpty();
		return company.getProducts();
	}

	private HomeInsuranceCompany assertHomeInsuranceBrand(final ResidentialDomain residentialDomain, final HomeInsuranceBrand brand) {
		assertThat(brand.getName()).isNotNull().isEqualTo(residentialDomain.getBrandName());
		assertThat(brand.getCompany()).isNotNull();
		assertThat(brand.getCompany().size()).isEqualTo(1);
		return brand.getCompany().get(0);
	}

	private HomeInsuranceBrand assertResponseHomeInsuranceListData(final ResponseHomeInsuranceListData responseHomeInsuranceListData) {
		assertThat(responseHomeInsuranceListData).isNotNull();
		assertThat(responseHomeInsuranceListData.getBrand()).isNotNull();
		return responseHomeInsuranceListData.getBrand();
	}

	private Page<ResidentialDomain> getPageResponse() {
		var residentialOne = DummyObjectsUtil.newInstance(ResidentialDomain.class);
		var residentialTwo = DummyObjectsUtil.newInstance(ResidentialDomain.class);
		var residentialThree = DummyObjectsUtil.newInstance(ResidentialDomain.class);

		return new PageImpl<>(List.of(residentialOne, residentialTwo, residentialThree));
	}

}