package br.com.bradescoseguros.opin.interfaceadapter.autogenerated;

import br.com.bradescoseguros.opin.ContextTest;
import br.com.bradescoseguros.opin.domain.rangecep.ResidentialRangeCep;
import br.com.bradescoseguros.opin.domain.residential.ResidentialDomain;
import br.com.bradescoseguros.opin.dummy.DummyObjectsUtil;
import br.com.bradescoseguros.opin.interfaceadapter.repository.ResidentialRangeCepRepository;
import br.com.bradescoseguros.opin.interfaceadapter.repository.ResidentialRepository;
import org.apache.commons.lang3.ObjectUtils;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

//@AutoConfigureMockMvc
//class HomeInsuranceApiControllerTest extends ContextTest {
class HomeInsuranceApiControllerTest {

//    private final MockMvc mockMvc;
//    private final ResidentialRangeCepRepository residentialRangeCepRepository;
//    private final ResidentialRepository residentialRepository;
//
//    private static final String URL_TEMPLATE = "/open-insurance/products-services/v1/home-insurance/commercializationArea/{commercializationArea}";
//
//    private ResidentialRangeCep rangeCep;
//    private ResidentialDomain residential;
//
//    @Autowired
//    public HomeInsuranceApiControllerTest(MockMvc mockMvc, ResidentialRangeCepRepository residentialRangeCepRepository,
//                                          ResidentialRepository residentialRepository) {
//        this.mockMvc = mockMvc;
//        this.residentialRangeCepRepository = residentialRangeCepRepository;
//        this.residentialRepository = residentialRepository;
//    }
//
//    @AfterEach
//    void cleanUp() {
//        if (ObjectUtils.isNotEmpty(this.rangeCep)) {
//            this.residentialRangeCepRepository.delete(this.rangeCep);
//        }
//        if (ObjectUtils.isNotEmpty(this.residential)) {
//            this.residentialRepository.delete(this.residential);
//        }
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withValidCepAndProductCode_shouldBeReturnSuccessfullyResult() throws Exception {
//        // Arrange
//        String cep = "12345678";
//        String productCode = "123";
//        this.rangeCep = DummyObjectsUtil.newInstance(ResidentialRangeCep.class);
//        rangeCep.setPostalCodeStart(cep);
//        rangeCep.setPostalCodeEnd(cep);
//        rangeCep.setProductCode(productCode);
//
//        this.residential = DummyObjectsUtil.newInstance(ResidentialDomain.class);
//        residential.getProduct().setCode(productCode);
//
//        // Act
//        residentialRangeCepRepository.save(this.rangeCep);
//        residentialRepository.save(this.residential);
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andExpect(status().isOk());
//
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withCepWithoutProducts_shouldBeNoContentResult() throws Exception {
//
//        // Arrange
//        String cep = "87654321";
//        String productCode = "321";
//        this.rangeCep = DummyObjectsUtil.newInstance(ResidentialRangeCep.class);
//        rangeCep.setPostalCodeStart(cep);
//        rangeCep.setPostalCodeEnd(cep);
//        rangeCep.setProductCode(productCode);
//
//        // Act
//        residentialRangeCepRepository.save(this.rangeCep);
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andExpect(status().is(HttpStatus.NO_CONTENT.value()));
//
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withCepOutOfRange_shouldBeNoContentResult() throws Exception {
//
//        // Arrange
//        String searchCep = "00000098";
//
//        // Act
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, searchCep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andExpect(status().is(HttpStatus.NO_CONTENT.value()));
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withoutCep_shouldBeNotFound() throws Exception {
//
//        // Arrange
//        String searchCep = "";
//
//        // Act
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, searchCep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andExpect(status().is(HttpStatus.NOT_FOUND.value()));
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withInvalidPageAndZipCodeThatContainsProducts_shouldBeNoContentResult() throws Exception {
//
//        // Arrange
//        String cep = "12345678";
//
//        // Act
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1")
//                        .param("page", "-1"))
//                .andExpect(status().is(HttpStatus.BAD_REQUEST.value()));
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withInvalidPageSizeByHugeValueAndZipCodeThatContainsProducts_shouldBeNoContentResult() throws Exception {
//
//        // Arrange
//        String cep = "12345678";
//
//        // Act
//        mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1")
//                        .param("page-size", "1050"))
//                .andExpect(status().is(HttpStatus.BAD_REQUEST.value()));
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withInvalidCepBySize_shouldBeBadRequest() throws Exception {
//
//        //Arrange
//        String cep = "123456789";
//
//        //Act
//        MvcResult mvcResult = mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andReturn();
//
//
//        assertThat(mvcResult.getResponse().getStatus()).isEqualTo(HttpStatus.BAD_REQUEST.value());
//
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withInvalidCepByChars_shouldBeBadRequest() throws Exception {
//
//        //Arrange
//        String cep = "12345abc";
//
//        //Act
//        MvcResult mvcResult = mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON)
//                        .header("cache-control", "1"))
//                .andReturn();
//
//
//        assertThat(mvcResult.getResponse().getStatus()).isEqualTo(HttpStatus.BAD_REQUEST.value());
//
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withoutCacheControl_shouldBeBadRequest() throws Exception {
//
//        //Arrange
//        String cep = "12345abc";
//
//        //Act
//        MvcResult mvcResult = mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .contentType(MediaType.APPLICATION_JSON))
//                .andReturn();
//
//
//        assertThat(mvcResult.getResponse().getStatus()).isEqualTo(HttpStatus.BAD_REQUEST.value());
//
//    }
//
//    @Test
//    @Tag("integration")
//    void getProducts_withAcceptMediaTypeApplicationXML_shouldBeBadRequest() throws Exception {
//
//        //Arrange
//        String cep = "12345678";
//
//        //Act
//        MvcResult mvcResult = mockMvc.perform(MockMvcRequestBuilders.get(URL_TEMPLATE, cep)
//                        .accept(MediaType.APPLICATION_XML)
//                        .header("cache-control", "1"))
//                .andReturn();
//
//        assertThat(mvcResult.getResponse().getStatus()).isEqualTo(HttpStatus.NOT_ACCEPTABLE.value());
//
//    }

}
